### ISSUE TITLE
Pool must be upgraded to set this property or value

### ISSUE THREAD

**Issue by bryanberger** [danb35/freenas-iocage-nextcloud#34]
Is a certain version of ZFS required?

**error i'm getting**

```
Creating tank/iocage
pool must be upgraded to set this property or value
```

**my pool's version**
```
NAME       PROPERTY  VALUE    SOURCE
tank       version   28       local
```

**Comment by bryanberger** [comment]
`zpool upgrade` fixes this. Would it be worth mentioning in the Readme what version of ZFS is required perhaps?

**Comment by danb35** [comment]
I wasn't aware of any particular pool version requirement, but it's been a good many years since a discrete version number was used (a bit of Googling suggests that v28 is 7 years old, having long since been replaced with "v5000" indicating feature flag support).  It's likely that there's a particular feature flag needed, but I'll need to see which one.

**Comment by bryanberger** [comment]
Hmm, thanks for the insight. That makes sense, I tested this on an old pool of mine (not sure that it’s 7yrs old though)

**Comment by danb35** [comment]
On further review, it looks like the change in FreeNAS took place between
the 8.3 series (which used ZFS v28) and the 9.1 series (which used feature
flags).  FreeNAS 9.1.0 was released on 27 Aug 13, not quite five years ago.
