### ISSUE TITLE
permission error on default.json

### ISSUE THREAD

**Issue by cperoni** [danb35/freenas-iocage-nextcloud#67]
Hello,

i would like to create a Nextcloud jails with your script but when i launch i have this error:

PermissionError: [Errno 1] Operation not permitted: '/mnt/<poolName>/iocage/defaults.json'

I run the script with user root and the script is executable.

Any ideas?

thanks

**Comment by danb35** [comment]
I thought I'd responded to this this morning, but I don't see it here.  The error is curious, as I don't recall that the script references a `defaults.json` file in any way.  Can you give a bit more context surrounding this error?  And what exactly are you doing that gives this result?

**Comment by cperoni** [comment]
Ok i try to explain the process:

i have one pool with 2 dataset, one called iocage and olther with my data.
With web interface i have downloaded 3 plugin: plex, trasmission and nextcloud.
But i want use your script to create a new jail bracause a want to access my nas from internet. So the name and the IP in the script are different from jail that exist.

I read and done any steps on your guide:
- I have cloned your project on dataset of data
- I have created the config file following your guide
- I'm registered on freenom, cloudflare, DNSoMatic 

Finally,with root account, i have launched the script from putty.

**Comment by Ornias1993** [comment]
/mnt/iocage/defaults.json is a buildin part of iocage.
This error would be during build or (re)start of the jail and is not (directly) related to this script.

Also: Supported FreeNAS version is now 11.3, which includes a MAJOR version upgrade for iocage. So this Issue is not relevant anymore for current version of this script.

ergo.
@danb35 This can be closed.
