### ISSUE TITLE
This vs freenas/iocage-plugin-nextcloud

### ISSUE THREAD

**Issue by aserrallerios** [danb35/freenas-iocage-nextcloud#69]
Differences? Why both exist? Is this better method than the curated plugin?

**Comment by danb35** [comment]
Here are a few differences:

* This script gives you a complete, ready-to-use Nextcloud installation,
while the plugin doesn't (at least not yet).
* This script uses Caddy as the web server rather than Nginx
* This script can configure TLS for your Nextcloud installation, including
automatically obtaining and renewing trusted certs from Let's Encrypt.

Further discussion would be better on the forum threads:
https://forum.freenas-community.org/t/scripted-installation-of-nextcloud-16-in-an-iocage-jail/25
or
https://www.ixsystems.com/community/threads/scripted-installation-of-nextcloud-16-in-iocage-jail.62485/

**Comment by aserrallerios** [comment]
Very good summary :) Thanks!
